// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVyk3OrXXOy3Ea6asXZQdts8WJwOueGac',
    appId: '1:240521187509:web:3b945d635a941b7c712efc',
    messagingSenderId: '240521187509',
    projectId: 'insta-clone-5c326',
    authDomain: 'insta-clone-5c326.firebaseapp.com',
    storageBucket: 'insta-clone-5c326.appspot.com',
    measurementId: 'G-4VNQVF0NRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIINJT5xLJQ75_AbyK6GZH1iPPUVBI7Ao',
    appId: '1:240521187509:android:f8a6c44404dd6da8712efc',
    messagingSenderId: '240521187509',
    projectId: 'insta-clone-5c326',
    storageBucket: 'insta-clone-5c326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQAECb4ejWOld6fjNa-pYSW2VPr5SI9vI',
    appId: '1:240521187509:ios:be85d3b6cc18a144712efc',
    messagingSenderId: '240521187509',
    projectId: 'insta-clone-5c326',
    storageBucket: 'insta-clone-5c326.appspot.com',
    iosClientId: '240521187509-b2oum12afdsms4o1j74kt3bkrpjifr0c.apps.googleusercontent.com',
    iosBundleId: 'usj.prac.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQAECb4ejWOld6fjNa-pYSW2VPr5SI9vI',
    appId: '1:240521187509:ios:be85d3b6cc18a144712efc',
    messagingSenderId: '240521187509',
    projectId: 'insta-clone-5c326',
    storageBucket: 'insta-clone-5c326.appspot.com',
    iosClientId: '240521187509-b2oum12afdsms4o1j74kt3bkrpjifr0c.apps.googleusercontent.com',
    iosBundleId: 'usj.prac.instaClone',
  );
}
